version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/public"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
