language: rust

before_install:
  - rustup component clippy rustfmt

rust:
  - stable
  - beta
  - nightly

cache: cargo

jobs:
  include:
    - name: Lint and format check
      rust: stable
      script:
        - cargo fmt --verbose -- --check
        - cargo clippy
  allow_failures:
    - rust: nightly
    - rust: beta

  fast_finish: true
