language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

jobs:
  include:
    - name: Lint and format check
      before_install:
        - rustup component add clippy rustfmt
      rust: stable
      script:
        - cargo fmt --verbose -- --check
        - cargo clippy --verbose
  allow_failures:
    - rust: nightly
    - rust: beta

  fast_finish: true
