[package]
name = "corewa_rs"
version = "0.1.0"
authors = ["Ian Chamberlain <ian.h.chamberlain@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
nom = "3.2.1"
pest_derive = "2.1.0"
pest = "2.1.0"
