[package]
name = "corewars-core"
version = "0.0.0"
authors = ["Ian Chamberlain <ian@corewa.rs>"]
edition = "2018"
description = "A placeholder subcrate for corewars"
license = "MIT"
repository = "https://github.com/corewa-rs/corewars"

[dependencies]
itertools = "0.9.0"
lazy_static = "1.4.0"
