name: ci

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

defaults:
  run:
    working-directory: redcode

jobs:
  build_redcode:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm install --locked
    - name: Build extension
      run: npm run build
    - name: Verify the build did not modify any files
      run: git diff --exit-code HEAD -- .

  lint_rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup default Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy,rustfmt
      - name: Check formatting
        run: cargo fmt --all --verbose -- --check
      - name: Run clippy linting
        run: cargo clippy --color=always --workspace --verbose --all-targets
        env:
          RUSTFLAGS:
            "-D warnings"

  validate_rust:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        toolchain:
          - stable
          - beta
          - nightly
    continue-on-error: ${{ matrix.toolchain != 'stable' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Build and run tests
        run: cargo test --color=always --workspace
