name: ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup default Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Setup problem matchers
        uses: r7kamura/rust-problem-matchers@v1

      - name: Check formatting
        run: cargo fmt --all --verbose -- --check

      - name: Run clippy linting
        run: cargo clippy --color=always --workspace --verbose --all-targets
        env:
          RUSTFLAGS:
            --warn=clippy::pedantic

  validate:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        toolchain:
          - stable
          - beta
          - nightly
    continue-on-error: ${{ matrix.toolchain != 'stable' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Setup problem matchers
        uses: r7kamura/rust-problem-matchers@v1

      - name: Build and run tests
        run: cargo test --color=always --workspace
