name: ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup default Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy,rustfmt
          toolchain: stable

      - name: Check formatting
        run: cargo fmt --all --verbose -- --check

      - name: Run clippy linting
        run: cargo clippy --color=always --workspace --verbose --all-targets
        env:
          # TODO: fix cast warnings
          RUSTFLAGS:
            --deny=warnings
            --deny=clippy::pedantic
            --allow=clippy::cast_possible_wrap
            --allow=clippy::cast_possible_truncation

  validate:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        toolchain:
          - stable
          - beta
          - nightly
    continue-on-error: ${{ matrix.toolchain != 'stable' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Build and run tests
        run: cargo test --color=always --workspace
