name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup default Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install cargo-workspaces
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-workspaces

    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo workspaces publish --yes --from-git --allow-branch develop
